### PR TITLE
Tc 7:  reckless_mode can now be set as environment variable #TC-7

### PR DESCRIPTION
**Pull request by michaelgaida**
`TC_RECKLESS_MODE=yes`

### CODE REVIEW

**Comment by gerva** [comment]
Looks good to me, I think we should create a config module into lib/. 
`lib/tc.py` is becoming too complex and it's better to refactor it now. @michaelgaida what do you think?

**Comment by michaelgaida** [comment]
@gerva yes, absolutely.

**Comment by michaelgaida** [comment]
Have a look @gerva. Restructured and cleanup.

**Review by gerva — APPROVED** [review]

**Comment by gerva** [comment]
Thank you @michaelgaida

**Pull request merged**
